version: "3.3"

services:
    # NGINX CONTAINER
    nginx:
        image: nginx:stable-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ../:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network

    # FPM CONTAINER
    app:
        build:
            context: ./php-fpm
            args:
                - NODE_VERSION=${NODE_VERSION}
            dockerfile: ./Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-app
        restart: unless-stopped
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ../:/var/www
            - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./php-fpm/supervisord.conf:/etc/supervisord.conf
        networks:
            - app-network

    # REDIS CONTAINER
    redis:
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        image: redis:alpine
        ports:
          - "${REDIS_PORT}:6379"
        environment:
          - REDIS_HOST=${REDIS_HOST}
          - REDIS_PORT=6379
          - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: --requirepass ${REDIS_PASSWORD}
        volumes:
          - redis_data:/data
        networks:
          - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge

# Docker Volumes
volumes:
  redis_data:
